### PR TITLE
Dynamic framework

### PR DESCRIPTION
**Pull request by akolov**
Created iOS 8 dynamic framework target

### CODE REVIEW

**Comment by nonelse** [comment]
Thanks! We'll try it to include in the next version.
Is there any instructions to test it?

**Comment by akolov** [comment]
You can build the framework manually or include via Carthage (https://github.com/Carthage/Carthage). Either way you need to add it to the project's linked and embedded frameworks. For the real test I'd also build the test app for the device with distribution profile (this will also test complete signing chain).
In case of fail the app would crash on first Adjust call with "dyld: Library not loaded" message.

**Comment by fjolnir** [comment]
+1

**Comment by uerceg** [comment]
Sorry guys for delay, we are preparing Adjust dynamic framework and it will most probably become part of one of our next SDK updates.

**Comment by MrPleaze2015** [comment]
Thanks for this update! We are 1FOREVER

**Comment by uerceg** [comment]
@akolov Thanks once more for your PR, but we did it on our own in #147. Cheers!

**Pull request closed without merging**
