### PR TITLE
Make more swifty interface

### PR DESCRIPTION
**Pull request by d-date**
In the view of Swift developer, the interfaces for Swift is not suitable.

In this PR, with little braking change for Swift developer, improve Swift interface.

### Before

```swift
let environment = ADJEnvironmentSandbox
let adjustConfig = ADJConfig(appToken: appToken, environment: environment)
adjustConfig.logLevel = ADJLogLevelVerbose
Adjust.appDidLaunch(adjustConfig)

let event = ADJEvent(eventToken: "token")
Adjust.trackEvent(event)
```

### After
```swift
let environment: Environment = .sandbox // enum
let adjustConfig = Config(appToken: appToken, environment: environment) // remove ADJ prefix
adjustConfig.logLevel = .verbose // enum
Adjust.appDidLaunch(config: adjustConfig) // parameter label

let event = Event(eventToken: "token") // remove ADJ prefic
Adjust.track(event: event) // refine with parameter label
```

We have more improvement. see AppDelegate.swift and ViewControllerSwift.swift.

### CODE REVIEW

**Comment by d-date** [comment]
How are you guys?

**Comment by nonelse** [comment]
Hi @d-date, thanks for the PR and suggestions.

Most of them make sense, but we might need to change it to lessen the impact of updating to them.

I think most if not all would be a breaking change, that we are not looking for to update the SDK version for, but I think we can compromise with some common sense things:

1. I think the class names can still be `ADJ` prefixed. Swift still does not have proper namespaces, and `Attribution` or `Event` are still generic enough to distinguish them.
The method name change to have named parameters for all parameters makes sense. 👍 

2. The lightweight generics in objective-c also make sense, and as far as I found it's just limited by Xcode 7.0, correct?

3. `instancetype` for `id` also makes sense for type checking. 👍 

4. I'm not so sure about `nullable` to `nonnull` for the constructors. Doesn't the check `if (self == nil) return nil;` at every constructor init invalidate this assurance?

5. Use of `NS_ENUM` also makes sense 👍 

6. Not so sure about using `NS_EXTENSIBLE_STRING_ENUM` with its limitation of Xcode 8+
7. Or typedef const string to `ADJEnvironment`
8. Or moving it from `Adjust.h/m` to `ADJConfig.h/m`

**Comment by d-date** [comment]
@nonelse
Thank you for your review.

> I think the class names can still be ADJ prefixed. Swift still does not have proper namespaces, and Attribution or Event are still generic enough to distinguish them.

In Swift, module has something like namespace, so user can use `Adjust.Config` instead of `ADJConfig`.
If user already implemented their `Config`, It’s distinguished with `<AppName>.Config` so conflict has not occurred. ADJ prefix does not make sense for Swift API Guideline.

> The lightweight generics in objective-c also make sense, and as far as I found it's just limited by Xcode 7.0, correct?

YES. lightweight generics can use from Xcode 7.0. See release note and WWDC session.

Nonnull, nulllable only affect for Swift interface, so we still need nil check in initializer of Objective-C.

> `NS_EXISTENSIB_STRING_ENUM` 

is available from XCode8

I think `ADJEnviroment` should be enum for user with limited values. In this change, when `ADJEnvironment` written in `Adjust.h/m`, ADJConfig cannot use ADJEnvironment with redundant defined so that I moved.

**Comment by d-date** [comment]
@nonelse  @uerceg How about this PR?

**Comment by JackTudor96** [comment]
@d-date @nonelse any update on this? the enums are better and using the parameters

**Comment by d-date** [comment]
I've lost interest for Adjust and no longer use it.

**Pull request closed without merging**
