### PR TITLE
Version 4.28.0

### PR DESCRIPTION
**Pull request by nonelse**
- Remove legacy code

### CODE REVIEW

**Comment by kantanta** [comment]
Hi @uerceg 
Today our app was rejected for the following reason:
"Specifically, your app uses algorithmically converted device and usage data to create a unique identifier in order to track the user. The device information collected by your app may include some of the following: Adjust."

I see you have removed all this staff from SDK. 
Could you tell does it fix the reason for rejection?

Thank you.

**Comment by uerceg** [comment]
Hi @kantanta 

We received reports that some app updates using our SDK v4.27.x and lower have been rejected by Apple. To address this problem, we have released v4.28.0. We recommend that all clients upgrade to SDK v4.28.0 before submitting their next app update.

We are actively following the submission review process and will keep you updated.

Feel free to reach out if you have any questions.

Cheers

**Comment by kantanta** [comment]
We will try.
Thanks, @uerceg

**Comment by chuganzy** [comment]
Hi @uerceg 
I saw [this tweet](https://twitter.com/eric_seufert/status/1377644555051356165) indicating that even after this upgrade Apple still declines. Is that what you are also observing? Also I am curious where to get these latest updates from Adjust.

**Comment by uerceg** [comment]
Hi @chuganzy 

All apps that resubmitted with 4.28 have been consistently approved. We were not giving the go ahead to our clients before we had confirmation from enough apps so that might be what the tweet is referencing. However, you are good to go with the 4.28 update.

Cheers

**Comment by chuganzy** [comment]
@uerceg Thank you for your confirmation and it sounds great. Let us try and see how it goes. We will keep you posted.

**Comment by kantanta** [comment]
@uerceg Two our apps successfully passed review after update SDK to 4.28

**Comment by uerceg** [comment]
Great news, thanks for the update!

**Comment by chuganzy** [comment]
@uerceg Sorry to be late but our app also has passed with this update!

**Pull request merged**
