### PR TITLE
removed FB

### PR DESCRIPTION
**Pull request by gioe**

### CODE REVIEW

**Comment by abekert** [comment]
Are you also experiencing freeze at this step on the app start?

**Comment by uerceg** [comment]
Added in https://github.com/adjust/ios_sdk/releases/tag/v4.18.3.

**Comment by uerceg** [comment]
@abekert ☝️ Feel free to give `v4.18.3` a shot, we removed this peace of code completely from there.

**Comment by abekert** [comment]
Just to confirm the freeze has gone with `v4.18.3`

**Comment by uerceg** [comment]
Thanks for confirmation!

**Pull request closed without merging**
