### PR TITLE
Fix README import typo

### PR DESCRIPTION
**Pull request by ersentekin**

### CODE REVIEW

**Comment by uerceg** [comment]
@ersentekin Thanks for the PR, but import we are having at the moment is the proper one. We have renamed our library name from `Adjust` to `AdjustSdk` to keep the name consistent in static and dynamic framework.

Which SDK version are you using?

**Comment by ersentekin** [comment]
Hey,
I'm using 4.6.0 and I realized that I need to type import <Adjust/Adjust.h>
. Will "AdjustSdk" name conversion be available for the next releases?

On Tue, Apr 12, 2016 at 2:35 PM, Uglješa Erceg <notifications@github.com>
wrote:

> @ersentekin <https://github.com/ersentekin> Thanks for the PR, but import
> we are having at the moment is the proper one. We have renamed our library
> name from Adjust to AdjustSdk to keep the name consistent in static and
> dynamic framework.
>
> Which SDK version are you using?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/adjust/ios_sdk/pull/183#issuecomment-208857927>
>



-- 
*Ersen Tekin*
*ersentekin.com <http://ersentekin.com>*

**Comment by uerceg** [comment]
Hm. How are you adding our SDK to your app (static/dynamic framework, from source or from Pods/Carthage)? In version 4.6.0 if you choose to add our SDK as static framework, import statement in the code should look like this:

```
#import <AdjustSdk/Adjust.h>
```

We introduced this name change in this SDK release: https://github.com/adjust/ios_sdk/releases/tag/v4.5.0

**Comment by ersentekin** [comment]
I'm adding via Cocoapods. Is it normal behaviour for Pods? (using the old
name)

On Tue, Apr 12, 2016 at 2:47 PM, Uglješa Erceg <notifications@github.com>
wrote:

> Hm. How are you adding our SDK to your app (static/dynamic framework, from
> source or from Pods/Carthage)? In version 4.6.0 if you choose to add our
> SDK as static framework, import statement in the code should look like this:
>
> #import <AdjustSdk/Adjust.h>
>
> We introduced this name change in this SDK release:
> https://github.com/adjust/ios_sdk/releases/tag/v4.5.0
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/adjust/ios_sdk/pull/183#issuecomment-208860575>
>



-- 
*Ersen Tekin*
*ersentekin.com <http://ersentekin.com>*

**Comment by uerceg** [comment]
Ah, okay, I see. In our example app, when using Pods, we are including our SDK like this:
```
#import "Adjust.h"
```
and that's it, it works. But thing you are using:
```
#import <Adjust/Adjust.h>
```
is working as well and is okay to be used, since our Pod wasn't renamed, it's called `Adjust`.

So, your PR is overwriting the stuff which are correct, but I will build upon it and make small adjustments to include this import command of yours to README as well.

Thank you for this. Will be added soon to official README.

**Comment by ersentekin** [comment]
Thanks for your interest Ugljesa! :) I think my PR overriding some correct
stuff so you should not accept it, right? If its okay, im going to remove
my PR

On Tue, Apr 12, 2016 at 3:27 PM, Uglješa Erceg <notifications@github.com>
wrote:

> Ah, okay, I see. In our example app, when using Pods, we are including our
> SDK like this:
>
> #import "Adjust.h"
>
> and that's it, it works. But thing you are using:
>
> #import <Adjust/Adjust.h>
>
> is working as well and is okay to be used, since our Pod wasn't renamed,
> it's called Adjust.
>
> So, your PR is overwriting the stuff which are correct, but I will build
> upon it and make small adjustments to include this import command of yours
> to README as well.
>
> Thank you for this. Will be added soon to official README.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/adjust/ios_sdk/pull/183#issuecomment-208879343>
>



-- 
*Ersen Tekin*
*ersentekin.com <http://ersentekin.com>*

**Comment by uerceg** [comment]
Yeah, pretty much it does that thing. :) If you want, you can close it, but point taken, we will update the README with instructions for your use case as well. 👍

**Comment by ersentekin** [comment]
Okay thanks so much for your interest! 🙂

12 Nisan 2016 Salı tarihinde, Uglješa Erceg <notifications@github.com>
yazdı:

> Yeah, pretty much it does that thing. :) If you want, you can close it,
> but point taken, we will update the README with instructions for your use
> case as well. 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/adjust/ios_sdk/pull/183#issuecomment-209001171>
>


-- 
*Ersen Tekin*
*ersentekin.com <http://ersentekin.com>*

**Pull request closed without merging**
