### PR TITLE
Add support for any SwiftPM-based dependency manager 

### PR DESCRIPTION
**Pull request by Jeehut**
This adds a very basic [SwiftPM](https://github.com/apple/swift-package-manager) manifest file to be compatible with any dependency manager that uses Apples official way of specifying libraries.

Note that I created this PR because I'm currently developing a dependency manager called [Accio](https://github.com/JamitLabs/Accio) which is intended to fix several issues with Carthage and fill the gap between now and the time, when Apple adds official support for SwiftPM into Xcode. Merging this will also prepare for that bright future.

### CODE REVIEW

**Comment by gabrielPeart** [comment]
It is vital to add support to Swift Package Manager

**Comment by Dschee** [comment]
@gabrielPeart I'm sorry, I just had a look into the checks, but I don't understand why any tests would fail just because I added a `Package.swift` file into the project. I don't see how these two things are related, it shouldn't fail in the first place ...

**Comment by gabrielPeart** [comment]
@Dschee Indeed, it should not have correlation with the failing test.

**Comment by gabrielPeart** [comment]
Any update?

**Comment by uerceg** [comment]
Hey guys, sorry for a bit of delay on this topic. We will try to find some time to check this topic in next couple of weeks. In case you're willing to give us some quick guidance and save us some time - is there a way to test if this PR works well in SPM and if yes, what would be the steps to test?

**Comment by Dschee** [comment]
It depends what you want to test. I already tested that it works with Accio. If you want to test if it works with SwiftPM integration into Xcode 11, then you just need to create a new project with Xcode 11 beta and add this project as a dependency (using my fork). See [this WWDC session](https://developer.apple.com/videos/play/wwdc2019/408/) for more information on how to do that. Please note that there was also a session about how to [create a package](https://developer.apple.com/videos/play/wwdc2019/410/) in case you want to check it out, too.

**Comment by micheltlutz** [comment]
Any Update?

**Comment by mayur-ios-dev** [comment]
Any updates here?

**Comment by blainesolomon** [comment]
I'd love to get a response from @uerceg

**Comment by uerceg** [comment]
Hey guys, thanks for following up and sorry for delays. We are currently working on iOS SDK update which will, next to one feature, try to address [this issue](https://github.com/adjust/ios_sdk/issues/350) and hopefully this topic as well. We are actively starting to take a look at this topic as of next week.

**Comment by uerceg** [comment]
@Jeehut Did you manage to make this work for you in your app in this state of pull request? I [forked](https://github.com/uerceg/ios_sdk) the repo, added your changes to it + pushed new `v4.20.1` tag in the forked repo because Xcode was complaining about absence of `Package.swift` for latest official tag we have (I assume because your commits were added after tag was pushed).

In example app I am managing to see all the targets you have exposed in `Package.swift` and can select `AdjustSdk` framework from there, but that's as far as it goes. I see it being added to Swift example app, but if I attempt to reference anything from the framework, it doesn't seem to be working for me. Seeing pretty much stuff like this:

Screenshot 2020-03-11 at 12 54 21

Does it work for you or are there any additional integration steps one needs to perform after adding `AdjustSdk` through Swift Package Manager?

Looking forward to hear back from you on this one (or anyone else from the discussion if willing to take a look).

**Comment by uerceg** [comment]
Also @blainesolomon, @gabrielPeart, @mayur-ios-dev, @micheltlutz in case anyone of you guys is willing to look at the comment from above and give it a shot, would be great since we're planning to ship SDK update soon and would be good if we can bundle this in as well. Looking forward to hearing from you guys.

**Comment by Jeehut** [comment]
@uerceg Hey, sorry but I don't remember exactly the last state of this and I can't look it up as I moved to a different company since then. Maybe @fredpi or @mrylmz can help you there? (I think we used this on the telecast project from Bavaria, if you know what I mean :wink:).

**Comment by xav42mac** [comment]
Any updates ?

**Comment by uerceg** [comment]
Hi @xav42mac 

I tried to move things a bit in [this comment](https://github.com/adjust/ios_sdk/pull/370#issuecomment-597590457). Is there any chance you can give adding SDK a shot through Swift Package Manager through that fork a shot? Fork pretty much contains what this PR suggested, but for me it didn't really work, so would be good to hear if it works for the others.

Cheers

**Comment by xav42mac** [comment]
Hi @uerceg 
I've correctly added this SDK via the fork of @Jeehut but it's seem to have a problem in a import.

Screen Shot 2020-05-15 at 15 13 06

A path problem ?

Screen Shot 2020-05-15 at 15 16 41

**Comment by uerceg** [comment]
Hi @xav42mac 

I am actually seeing that error as well (among many others, but maybe others are caused by target not properly building due to that one 🤷). I am not sure where is this coming from. By looking at changes @Jeehut made, seems to me like [here](https://github.com/adjust/ios_sdk/pull/370/files#diff-37ca2dd15ca0f6b1b49e78db084ef5b9R15) might be the issue.

But to be honest, I do not know SPM syntax and how to add multiple paths to this line (to say to look into `Adjust/ADJAdditions` as well and not just in `Adjust` folder; or somehow just look to Adjust and every possible subdirectory). Any idea maybe how this should be stated in `Package.swift` file?

**Comment by galip91** [comment]
Hi! Any updates regarding this? 🙂

**Comment by mstfy** [comment]
Hey @galip91 check #466

**Comment by ugi** [comment]
@Jeehut and everyone else participating in discussion/reactions, thank you one more time for contributions and patience. Replacing this PR with the official one which should add Swift Package Manager support (https://github.com/adjust/ios_sdk/pull/473).

**Comment by o15a3d4l11s2** [comment]
I am using the latest version (4.24.0) with SPM and I get an error `Value of type 'UIDevice' has no member 'adjIdForAdvertisers' `.

To me this seems related to the ADJAdditions issue.

How I use `adjIdForAdvertisers`:
```swift
if let idfa = UIDevice.current.adjIdForAdvertisers() {
    NSLog("To forget device in Adjust: https://app.adjust.com/forget_device?app_token=\(adjustToken)&idfa=\(idfa)")
}
```

I see `headerSearchPath("ADJAdditions")` in the Package.swift file, but I am not sure why it is not working.

**Comment by uerceg** [comment]
Hi @o15a3d4l11s2 

Hm. Is this code for getting IDFA somewhere in your app? In theory, you should not be trying to access that method which is part of `UIDevice` extension. `Adjust` API offers getter for IDFA which you should be using for this purpose.

Let us know if it worked for you.

Cheers

**Comment by o15a3d4l11s2** [comment]
Hi @uerceg, thanks for the update. The reason I am trying to access `UIDevice.current.adjIdForAdvertisers()` is exactly what I posted as code above, to print out in the console a quick message with link that I can easily open when I need to test something that requires forgetting my device beforehand 😊 

Is `UIDevice.current.adjIdForAdvertisers()` equivalent to `Adjust.idfa()`?

**Comment by uerceg** [comment]
Hi @o15a3d4l11s2,

Yes it is (https://github.com/adjust/ios_sdk/blob/master/Adjust/Adjust.m#L386, https://github.com/adjust/ios_sdk/blob/master/Adjust/ADJUtil.m#L525). So by calling public API method, exact same method you're trying to call will be called under the hood.

**Pull request closed without merging**
