### PR TITLE
fix memory  increase issue when continuous writing to file

### PR DESCRIPTION
**Pull request by huiping192**

### CODE REVIEW

**Comment by uerceg** [comment]
Hi @huiping192 ,

Thank you very much for the PR. Do you maybe have an example of the memory warning you were facing and which change from this PR has solved?

**Comment by uerceg** [comment]
Thank you for your contribution. Adding this change to v4.32.1 and replacing this PR with https://github.com/adjust/ios_sdk/pull/633. Please, keep us posted if this change solved your issues. Cheers.

**Comment by huiping192** [comment]
@uerceg   Sorry, i`m just forgot to update the pull request detail.    Thank you for adding the change.  ^^

**Comment by uerceg** [comment]
@huiping192 Not a problem at all. Just out of curiosity, were you experiencing just an increased memory consumption in these cases or did you face any crashes because of this issue?

**Comment by huiping192** [comment]
@uerceg    we face the crash because this issue.  In our product send continuous like 200~1000 events will case the memory warning and then app will crash after that.  If stop at middle of sending the events the memory usage will back to normal.

We checked that no happened after my commit.

(sorry about the janpanese commit log.. i just notice that. ><

**Comment by uerceg** [comment]
No worries at all about Japanese commit message. :) And thank you for additional infos. Can you maybe share crash log reports you were getting when app crashes in this case?

**Comment by huiping192** [comment]
Because this happened like 4 mouth ago, i did not keep the crash log. so sorry

**Pull request closed without merging**
